//creat a white background with a centered card with tailwind css
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"></link>

            </Head>
            <main className='main-content'>
                <div className={styles.description}>
                    {/* centered card */}
                    <div className="container py-5">
                        <div className="row">
                            <div className="col-md-6 offset-md-3">
                                <div className="card border-0 ">
                                    <div className="card-body ">
                                        <h1 className="text-4xl font-bold underline text-center">
                                            Welcome to 20Questions
                                        </h1>
                                        <p className='text-muted text-center'>
                                        Unlock free personalized financial advice with our AI-powered recommendations
                                        </p>

                                        <div className="form-group">
                                            <div className="row justify-content-center my-4">
                                                <input type="email" className="mx-1 col-5 form-control " id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="name"></input>
                                                <button type="submit" className="mx-1 col-2 btn btn-primary">Submit</button>
                                            </div>
                                        </div>
                                        <small id="emailHelp" className="form-text text-muted text-center">Enter your name to get started</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>

    )
}