//creat a white background with a centered card with tailwind css
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import React from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

function getQuestionText(index){
    
    const questions = ["What are your financial goals? This could include things like saving for retirement, paying off debt, buying a house, or funding a child's education.","Are you a student? If so, how much do you spend on your education early?"]
    //include a sanity check
    if(index > questions.length || index < 1){
        return "Error: question index out of bounds"
    }


    return questions[index-1]
}

function postQuestion(index,answer){
    //post the answer to the question at index
    console.log("question " + index + " answer: " + answer)
    
}

export default function q() {
    
    const router = useRouter()
    const { question } = router.query
    

    return (
        <>
            <Head>
                <title>Question {question}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"></link>

            </Head>
            <main className='main-content'>
                <div className={styles.description}>
                    {/* centered card */}
                    <div className="container py-5">
                        <div className="row">
                            <div className="col-md-6 offset-md-3">
                                <div className="card border-0 ">
                                    <div className="card-body ">
                                        <h1 className="text-4xl font-bold underline text-center">
                                        Question {question}
                                        </h1>
                                        <p className='text-2xl text-muted text-center'>
                                        {getQuestionText(parseInt(question))}
                                        </p>

                                        <div className="form-group">
                                            <div className="row justify-content-center my-4">
                                                <input type="email" className="mx-1 col-5 form-control " id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="response"></input>
                                                <Link className='mx-1 col-2' href={question>10 ? `/api` : ` /questions/${parseInt(question)+1}`}> 
                                                    <button type="submit" className=" btn btn-primary">Next</button>
                                                </Link>
                                            </div>
                                        </div>
                                        {/* <small id="emailHelp" className="form-text text-muted text-center">Enter your name to get started</small> */}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>

    )
}